import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL('https://www.pwnclaw.com'),
  title: {
    default: "PwnClaw — AI Agent Security Testing | Automated Pentesting for LLM Agents",
    template: "%s | PwnClaw",
  },
  description: "Test your AI agent against 50 randomized attacks from 112-attack library — prompt injection, jailbreaks, data exfiltration, Crescendo & more. Get fix instructions in 5 minutes. No API keys needed.",
  keywords: [
    "AI agent security testing",
    "AI agent pentesting",
    "prompt injection testing",
    "prompt injection scanner",
    "jailbreak detection",
    "LLM security scanner",
    "LLM security testing",
    "AI red teaming",
    "AI red team tool",
    "AI vulnerability scanner",
    "agent security audit",
    "prompt injection defense",
    "prompt injection prevention",
    "LLM pentesting tool",
    "AI agent hardening",
    "Crescendo attack testing",
    "data exfiltration prevention AI",
    "AI safety testing",
    "automated AI security",
    "MCP security testing",
    "AI agent vulnerability assessment",
    "LLM prompt attack",
    "AI chatbot security",
    "test AI agent security",
    "AI security tool",
    "OWASP LLM top 10",
  ],
  authors: [{ name: "PwnClaw" }],
  creator: "PwnClaw",
  publisher: "PwnClaw",
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large' as const,
      'max-snippet': -1,
    },
  },
  alternates: {
    canonical: 'https://www.pwnclaw.com',
  },
  openGraph: {
    title: "PwnClaw — AI Agent Security Testing",
    description: "50 randomized attacks from 112-attack library. Detailed vulnerability reports. Copy-paste fix instructions. Test your AI agent in 5 minutes.",
    url: 'https://www.pwnclaw.com',
    siteName: 'PwnClaw',
    locale: 'en_US',
    type: "website",
    // OG image is auto-generated by src/app/opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    title: "PwnClaw — AI Agent Security Testing",
    description: "50 randomized attacks from 112-attack library. Fix instructions included. No API keys needed.",
    creator: '@ClawdeRaccoon27',
    // Twitter image is auto-generated by src/app/opengraph-image.tsx
  },
  category: 'technology',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <html lang="en" className="dark">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
        >
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
