"use client";

import { useState, useEffect } from "react";
import { useParams, useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { 
  ArrowLeft, 
  CheckCircle, 
  XCircle, 
  AlertTriangle,
  ChevronDown,
  ChevronUp,
  Loader2,
  Shield,
  Trash2,
  Copy,
  Check,
  Wrench,
  RefreshCw,
  FileDown
} from "lucide-react";
import Link from "next/link";
import { getCategoryName } from "@/lib/utils";

type TestResult = {
  id: string;
  category: string;
  attackName: string;
  prompt?: string;
  promptPreview?: string;
  response: string;
  passed: boolean;
  severity: string | null;
  analysis: string;
};

type TestData = {
  test: {
    id: string;
    agentName: string;
    agentUrl: string | null;
    status: string;
    score: number | null;
    modelName: string | null;
    framework: string | null;
    createdAt: string;
    completedAt: string | null;
    withFixes?: boolean;
  };
  results: TestResult[];
  summary: {
    total: number;
    passed: number;
    failed: number;
    bySeverity: {
      critical: number;
      high: number;
      medium: number;
      low: number;
    };
  };
};

export default function TestDetailPage() {
  const params = useParams();
  const router = useRouter();
  const token = params.token as string;
  
  const [data, setData] = useState<TestData | null>(null);
  const [benchmark, setBenchmark] = useState<{ available: boolean; percentile?: number; totalScans?: number; avgScore?: number; medianScore?: number } | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [expandedResults, setExpandedResults] = useState<Set<string>>(new Set());
  const [deleting, setDeleting] = useState(false);
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);
  const [copiedFix, setCopiedFix] = useState(false);
  const [copiedBadge, setCopiedBadge] = useState(false);

  useEffect(() => {
    fetch(`/api/test/${token}/results`)
      .then(res => {
        if (!res.ok) throw new Error("Failed to load test");
        return res.json();
      })
      .then(d => {
        setData(d);
        // Fetch benchmark data if test has a score
        if (d.test?.score !== null && d.test?.score !== undefined) {
          fetch(`/api/benchmark?score=${d.test.score}`)
            .then(r => r.json())
            .then(setBenchmark)
            .catch(() => {}); // Benchmark is optional
        }
      })
      .catch(e => setError(e.message))
      .finally(() => setLoading(false));
  }, [token]);

  const copyFixInstructions = () => {
    if (!data) return;
    
    const failedTests = data.results.filter(r => !r.passed);
    if (failedTests.length === 0) return;
    
    // Extract fix instructions from analysis
    const getFixInstruction = (analysis: string) => {
      const parts = analysis.split('📋 Fix Instruction (copy-paste to your agent\'s system prompt):\n');
      return parts[1]?.trim() || null;
    };

    const fixInstructions = failedTests
      .map(r => getFixInstruction(r.analysis))
      .filter(Boolean);

    const instructions = `🛡️ SECURITY HARDENING — Add these rules to your system prompt:

${fixInstructions.length > 0 ? fixInstructions.join('\n\n') : failedTests.map((r, i) => `## ${i + 1}. ${r.attackName} (${r.severity?.toUpperCase() || 'MEDIUM'})
${r.analysis.includes('💡 Remediation:') ? r.analysis.split('💡 Remediation:')[1]?.split('\n\n')[0]?.trim() || 'Add explicit instructions to refuse this type of request.' : 'Add explicit instructions to refuse this type of manipulation.'}`).join('\n\n')}

---
These instructions were generated by PwnClaw (pwnclaw.com) after testing ${failedTests.length} vulnerabilit${failedTests.length === 1 ? 'y' : 'ies'}.
Add these rules as permanent instructions in your AI agent's system prompt, then run a re-test to verify the improvements.`;

    navigator.clipboard.writeText(instructions);
    setCopiedFix(true);
    setTimeout(() => setCopiedFix(false), 3000);
  };

  const handleDelete = async () => {
    setDeleting(true);
    try {
      const res = await fetch(`/api/test/${token}/delete`, { method: 'DELETE' });
      if (!res.ok) throw new Error('Failed to delete');
      router.push('/dashboard/tests');
    } catch (e) {
      setError('Failed to delete test');
      setDeleting(false);
      setShowDeleteConfirm(false);
    }
  };

  const toggleExpand = (id: string) => {
    const newExpanded = new Set(expandedResults);
    if (newExpanded.has(id)) {
      newExpanded.delete(id);
    } else {
      newExpanded.add(id);
    }
    setExpandedResults(newExpanded);
  };

  const severityColor = (severity: string | null) => {
    switch (severity) {
      case "critical": return "bg-red-500/10 text-red-500 border-red-500/20";
      case "high": return "bg-orange-500/10 text-orange-500 border-orange-500/20";
      case "medium": return "bg-yellow-500/10 text-yellow-500 border-yellow-500/20";
      case "low": return "bg-blue-500/10 text-blue-500 border-blue-500/20";
      default: return "bg-neutral-500/10 text-neutral-500 border-neutral-500/20";
    }
  };

  const gradeColor = (score: number) => {
    if (score >= 90) return "text-green-500";
    if (score >= 80) return "text-green-400";
    if (score >= 70) return "text-yellow-500";
    if (score >= 60) return "text-orange-500";
    return "text-red-500";
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <Loader2 className="w-8 h-8 text-green-500 animate-spin" />
      </div>
    );
  }

  if (error || !data) {
    return (
      <div className="p-8 max-w-3xl mx-auto">
        <Card className="bg-neutral-900 border-neutral-800">
          <CardContent className="py-12 text-center">
            <p className="text-red-400 mb-4">{error || "Test not found"}</p>
            <Link href="/dashboard/tests">
              <Button variant="outline">Back to Tests</Button>
            </Link>
          </CardContent>
        </Card>
      </div>
    );
  }

  const { test, results, summary } = data;
  const grade = test.score !== null 
    ? (test.score >= 90 ? "A" : test.score >= 80 ? "B" : test.score >= 70 ? "C" : test.score >= 60 ? "D" : "F")
    : "?";

  return (
    <div className="p-8 max-w-5xl mx-auto">
      {/* Header */}
      <div className="flex items-center gap-4 mb-8">
        <Link href="/dashboard/tests">
          <Button variant="ghost" size="icon" className="text-neutral-400 hover:text-white">
            <ArrowLeft className="w-5 h-5" />
          </Button>
        </Link>
        <div className="flex-1">
          <div className="flex items-center gap-2 flex-wrap">
            <h1 className="text-2xl font-bold text-white">{test.agentName}</h1>
            {test.agentUrl && (
              <a href={test.agentUrl} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 text-xs text-neutral-400 hover:text-neutral-200 bg-neutral-800 px-2 py-1 rounded-md transition-colors" title={test.agentUrl}>
                🔗 {test.agentUrl.length > 40 ? test.agentUrl.slice(0, 40) + '…' : test.agentUrl}
              </a>
            )}
            {(data as any)?.test?.isAdaptive && (
              <Badge className="bg-purple-500/10 text-purple-400 border-purple-500/20">
                🧠 Adaptive
              </Badge>
            )}
          </div>
          <div className="flex items-center gap-2 mt-1 flex-wrap">
            <p className="text-neutral-400 text-sm">
              {new Date(test.createdAt).toLocaleString()}
            </p>
            {test.modelName && (
              <Badge className="bg-blue-500/10 text-blue-400 border-blue-500/20">
                {test.modelName}
              </Badge>
            )}
            {test.framework && (
              <Badge className="bg-purple-500/10 text-purple-400 border-purple-500/20">
                {test.framework}
              </Badge>
            )}
            {test.withFixes ? (
              <Badge className="bg-green-500/10 text-green-400 border-green-500/20">
                🛡️ With PwnClaw Fixes
              </Badge>
            ) : (
              <Badge className="bg-neutral-500/10 text-neutral-400 border-neutral-500/20">
                Baseline
              </Badge>
            )}
          </div>
        </div>
        <div className="text-right">
          {test.score !== null ? (
            <>
              <div className={`text-4xl font-bold ${gradeColor(test.score)}`}>
                {test.score}/100
              </div>
              <div className="flex items-center gap-2 justify-end">
                <span className={`text-xl ${gradeColor(test.score)}`}>Grade {grade}</span>
                <Badge className="bg-neutral-800 text-neutral-400 border-neutral-700 text-xs">
                  {summary.total} attacks
                </Badge>
              </div>
              {test.completedAt && (
                <p className="text-xs text-neutral-500 mt-1">
                  ⏱️ Completed in {formatDuration(new Date(test.createdAt), new Date(test.completedAt))}
                </p>
              )}
            </>
          ) : (
            <>
              <div className="text-4xl font-bold text-neutral-500">—/100</div>
              <div className="text-xl text-neutral-500">{test.status === 'running' ? 'Running...' : test.status === 'waiting' ? 'Waiting...' : 'Pending...'}</div>
              {(test.status === 'running' || test.status === 'waiting') && (
                <ScanEstimateDetail createdAt={test.createdAt} />
              )}
            </>
          )}
        </div>
      </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-2 md:grid-cols-5 gap-4 mb-8">
        <Card className="bg-neutral-900 border-neutral-800">
          <CardContent className="py-4 text-center">
            <p className="text-2xl font-bold text-white">{summary.total}</p>
            <p className="text-xs text-neutral-500">Total Tests</p>
          </CardContent>
        </Card>
        <Card className="bg-neutral-900 border-neutral-800">
          <CardContent className="py-4 text-center">
            <p className="text-2xl font-bold text-green-500">{summary.passed}</p>
            <p className="text-xs text-neutral-500">Passed</p>
          </CardContent>
        </Card>
        <Card className="bg-red-500/10 border-red-500/20">
          <CardContent className="py-4 text-center">
            <p className="text-2xl font-bold text-red-500">{summary.bySeverity.critical}</p>
            <p className="text-xs text-red-400">Critical</p>
          </CardContent>
        </Card>
        <Card className="bg-orange-500/10 border-orange-500/20">
          <CardContent className="py-4 text-center">
            <p className="text-2xl font-bold text-orange-500">{summary.bySeverity.high}</p>
            <p className="text-xs text-orange-400">High</p>
          </CardContent>
        </Card>
        <Card className="bg-yellow-500/10 border-yellow-500/20">
          <CardContent className="py-4 text-center">
            <p className="text-2xl font-bold text-yellow-500">{summary.bySeverity.medium + summary.bySeverity.low}</p>
            <p className="text-xs text-yellow-400">Med/Low</p>
          </CardContent>
        </Card>
      </div>

      {/* Category Breakdown */}
      {results.length > 0 && (
        <Card className="bg-neutral-900 border-neutral-800 mb-6">
          <CardHeader>
            <CardTitle className="text-white text-sm">Security by Category</CardTitle>
          </CardHeader>
          <CardContent className="space-y-2">
            {(() => {
              const cats: Record<string, { passed: number; total: number }> = {};
              results.forEach(r => {
                if (!cats[r.category]) cats[r.category] = { passed: 0, total: 0 };
                cats[r.category].total++;
                if (r.passed) cats[r.category].passed++;
              });
              return Object.entries(cats)
                .sort(([,a], [,b]) => (a.passed/a.total) - (b.passed/b.total))
                .map(([cat, { passed, total }]) => {
                  const pct = Math.round((passed / total) * 100);
                  const barColor = pct === 100 ? 'bg-green-500' : pct >= 80 ? 'bg-green-500' : pct >= 60 ? 'bg-yellow-500' : pct > 0 ? 'bg-orange-500' : 'bg-red-500';
                  const bgColor = pct === 0 ? 'bg-red-500/10' : 'bg-neutral-800';
                  const barWidth = pct === 0 ? 5 : pct;
                  return (
                    <div key={cat} className="flex items-center gap-3">
                      <span className={`text-xs w-36 truncate ${pct === 0 ? 'text-red-400' : pct < 100 ? 'text-yellow-400' : 'text-neutral-400'}`}>{getCategoryName(cat)}</span>
                      <div className={`flex-1 rounded-full h-2 ${bgColor}`}>
                        <div
                          className={`h-2 rounded-full ${barColor}`}
                          style={{ width: `${barWidth}%` }}
                        />
                      </div>
                      <span className={`text-xs font-mono w-16 text-right ${pct === 100 ? 'text-green-400' : pct === 0 ? 'text-red-400' : 'text-yellow-400'}`}>{passed}/{total}</span>
                    </div>
                  );
                });
            })()}
          </CardContent>
        </Card>
      )}

      {/* Benchmark Comparison */}
      {benchmark?.available && (
        <Card className="bg-gradient-to-r from-blue-500/10 to-purple-500/10 border-blue-500/30 mb-6">
          <CardContent className="py-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-4">
                <div className="text-center">
                  <div className="text-3xl font-bold text-blue-400">{benchmark.percentile}%</div>
                  <div className="text-xs text-neutral-400">Percentile</div>
                </div>
                <div>
                  <p className="font-medium text-white">
                    Better than {benchmark.percentile}% of all tested agents
                  </p>
                  <p className="text-sm text-neutral-400">
                    Based on {benchmark.totalScans} scans • Average: {benchmark.avgScore}/100 • Median: {benchmark.medianScore}/100
                  </p>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Fix Instructions Button - Only show if there are vulnerabilities */}
      {summary.failed > 0 && (
        <Card className="bg-gradient-to-r from-yellow-500/10 to-orange-500/10 border-yellow-500/30 mb-6">
          <CardContent className="py-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <Wrench className="w-6 h-6 text-yellow-500" />
                <div>
                  <p className="font-medium text-white">Fix These Vulnerabilities</p>
                  <p className="text-sm text-neutral-400">Copy instructions to send to your AI agent for hardening</p>
                </div>
              </div>
              <Button 
                onClick={copyFixInstructions}
                className="bg-yellow-500 hover:bg-yellow-600 text-black font-semibold"
              >
                {copiedFix ? (
                  <>
                    <Check className="w-4 h-4 mr-2" />
                    Copied!
                  </>
                ) : (
                  <>
                    <Copy className="w-4 h-4 mr-2" />
                    Copy Fix Instructions
                  </>
                )}
              </Button>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Results List */}
      <Card className="bg-neutral-900 border-neutral-800">
        <CardHeader>
          <CardTitle className="text-white flex items-center gap-2">
            <Shield className="w-5 h-5 text-green-500" />
            Attack Results
          </CardTitle>
          <CardDescription>Click on any result to see details</CardDescription>
        </CardHeader>
        <CardContent className="space-y-2">
          {results.map(result => {
            const isExpanded = expandedResults.has(result.id);
            return (
              <div key={result.id} className="border border-neutral-800 rounded-lg overflow-hidden">
                <button
                  onClick={() => toggleExpand(result.id)}
                  aria-label={isExpanded ? "Collapse attack details" : "Expand attack details"}
                  className="w-full p-4 flex items-center justify-between hover:bg-neutral-800/50 transition"
                >
                  <div className="flex items-center gap-3">
                    {result.passed ? (
                      <CheckCircle className="w-5 h-5 text-green-500" />
                    ) : (
                      <XCircle className="w-5 h-5 text-red-500" />
                    )}
                    <div className="text-left">
                      <p className="font-medium text-white">{result.attackName}</p>
                      <p className="text-sm text-neutral-500">{getCategoryName(result.category)}</p>
                    </div>
                  </div>
                  <div className="flex items-center gap-3">
                    {!result.passed && result.severity && (
                      <Badge className={severityColor(result.severity)}>
                        {result.severity}
                      </Badge>
                    )}
                    {isExpanded ? (
                      <ChevronUp className="w-5 h-5 text-neutral-500" />
                    ) : (
                      <ChevronDown className="w-5 h-5 text-neutral-500" />
                    )}
                  </div>
                </button>
                
                {isExpanded && (
                  <div className="p-4 border-t border-neutral-800 bg-neutral-950 space-y-4">
                    <div>
                      <p className="text-xs text-neutral-500 mb-1">Attack Prompt</p>
                      <p className="text-sm text-neutral-300 bg-black p-3 rounded font-mono whitespace-pre-wrap">
                        {result.promptPreview || result.prompt}
                      </p>
                    </div>
                    <div>
                      <p className="text-xs text-neutral-500 mb-1">Agent Response</p>
                      <p className="text-sm text-neutral-300 bg-black p-3 rounded font-mono whitespace-pre-wrap max-h-48 overflow-y-auto">
                        {result.response}
                      </p>
                    </div>
                    <div>
                      <p className="text-xs text-neutral-500 mb-1">Analysis</p>
                      <div className={`p-3 rounded ${result.passed ? "bg-green-500/10 border border-green-500/20" : "bg-red-500/10 border border-red-500/20"}`}>
                        <p className="text-sm text-neutral-300 whitespace-pre-wrap">
                          {result.analysis?.split('\n\n📋 Fix Instruction')[0]}
                        </p>
                      </div>
                    </div>
                    {!result.passed && result.analysis?.includes('📋 Fix Instruction') && (
                      <div>
                        <div className="flex items-center justify-between mb-1">
                          <p className="text-xs text-yellow-500 font-semibold">📋 Fix Instruction — Copy & paste to your agent</p>
                          <button
                            aria-label="Copy fix instruction"
                            onClick={(e) => {
                              e.stopPropagation();
                              const fix = result.analysis.split('📋 Fix Instruction (copy-paste to your agent\'s system prompt):\n')[1] || '';
                              navigator.clipboard.writeText(fix.trim());
                              // Brief visual feedback
                              const btn = e.currentTarget;
                              btn.textContent = '✓ Copied!';
                              setTimeout(() => { btn.textContent = 'Copy'; }, 2000);
                            }}
                            className="text-xs px-2 py-1 rounded bg-yellow-500/20 text-yellow-400 hover:bg-yellow-500/30 transition"
                          >
                            Copy
                          </button>
                        </div>
                        <div className="p-3 rounded bg-yellow-500/10 border border-yellow-500/30 font-mono">
                          <p className="text-sm text-yellow-200 whitespace-pre-wrap">
                            {result.analysis.split('📋 Fix Instruction (copy-paste to your agent\'s system prompt):\n')[1]?.trim()}
                          </p>
                        </div>
                      </div>
                    )}
                  </div>
                )}
              </div>
            );
          })}
        </CardContent>
      </Card>

      {/* Share & Export */}
      {test.status === 'completed' && test.score !== null && (
        <div className="grid md:grid-cols-2 gap-4 mt-6">
          {/* README Badge */}
          <Card className="bg-neutral-900 border-neutral-800 flex flex-col">
            <CardContent className="py-5 flex flex-col flex-1">
              <div className="flex items-center gap-3 mb-4">
                <Shield className="w-5 h-5 text-green-500" />
                <div>
                  <p className="font-medium text-white">README Badge</p>
                  <p className="text-xs text-neutral-400">Show your security score in your README</p>
                </div>
              </div>
              <div className="flex items-center justify-center bg-black rounded-lg p-4 mb-4">
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img src={`/api/badge/${token}.svg`} alt="PwnClaw Score Badge" height={20} />
              </div>
              <div className="bg-black rounded p-2 font-mono text-xs text-neutral-400 overflow-x-auto mb-3">
                {`![PwnClaw Score](https://www.pwnclaw.com/api/badge/${token}.svg)`}
              </div>
              <div className="mt-auto">
              <Button
                variant="outline"
                className="w-full border-neutral-700 cursor-pointer"
                onClick={() => {
                  const md = `![PwnClaw Score](https://www.pwnclaw.com/api/badge/${token}.svg)`;
                  navigator.clipboard.writeText(md);
                  setCopiedBadge(true);
                  setTimeout(() => setCopiedBadge(false), 3000);
                }}
              >
                {copiedBadge ? (
                  <>
                    <Check className="w-4 h-4 mr-2" />
                    Copied!
                  </>
                ) : (
                  <>
                    <Copy className="w-4 h-4 mr-2" />
                    Copy Markdown
                  </>
                )}
              </Button>
              </div>
            </CardContent>
          </Card>

          {/* Export Report */}
          <Card className="bg-neutral-900 border-neutral-800 flex flex-col">
            <CardContent className="py-5 flex flex-col flex-1">
              <div className="flex items-center gap-3 mb-4">
                <FileDown className="w-5 h-5 text-blue-400" />
                <div>
                  <p className="font-medium text-white">Export Report</p>
                  <p className="text-xs text-neutral-400">Download full results as Markdown</p>
                </div>
              </div>
              <div className="bg-black rounded-lg p-4 mb-4 text-sm text-neutral-400 space-y-1">
                <p>📊 Score, grade &amp; benchmark percentile</p>
                <p>🔍 All attack results with details</p>
                <p>🔧 Fix instructions for every vulnerability</p>
                <p>📈 Category breakdown &amp; severity counts</p>
              </div>
              <div className="mt-auto">
              <Button
                variant="outline"
                className="w-full border-neutral-700 cursor-pointer"
                onClick={() => {
                  const md = generateMarkdownReport(test, results, summary, benchmark);
                  const blob = new Blob([md], { type: 'text/markdown' });
                  const url = URL.createObjectURL(blob);
                  const a = document.createElement('a');
                  a.href = url;
                  a.download = `pwnclaw-${test.agentName.replace(/\s+/g, '-').toLowerCase()}-${new Date(test.createdAt).toISOString().slice(0,10)}.md`;
                  a.click();
                  URL.revokeObjectURL(url);
                }}
              >
                <FileDown className="w-4 h-4 mr-2" />
                Download Report (.md)
              </Button>
              </div>
            </CardContent>
          </Card>
        </div>
      )}

      {/* Actions */}
      <div className="flex gap-4 mt-8">
        <Link href="/dashboard/tests" className="flex-1">
          <Button variant="outline" className="w-full border-neutral-700 cursor-pointer">
            Back to History
          </Button>
        </Link>
        <Link href={`/dashboard/tests/new?agent=${encodeURIComponent(test.agentName)}`} className="flex-1">
          <Button className="w-full bg-green-500 hover:bg-green-600 text-black cursor-pointer">
            <RefreshCw className="w-4 h-4 mr-2" />
            Re-Test {test.agentName}
          </Button>
        </Link>
      </div>

      {/* Delete Section */}
      <div className="mt-8 pt-8 border-t border-neutral-800">
        {!showDeleteConfirm ? (
          <Button 
            variant="outline" 
            className="border-red-500/50 text-red-500 hover:bg-red-500/10 cursor-pointer"
            onClick={() => setShowDeleteConfirm(true)}
          >
            <Trash2 className="w-4 h-4 mr-2" />
            Delete Test & All Data
          </Button>
        ) : (
          <div className="bg-red-500/10 border border-red-500/20 rounded-lg p-4">
            <p className="text-red-400 mb-4">
              ⚠️ This will permanently delete this test and all attack results. This cannot be undone.
            </p>
            <div className="flex gap-4">
              <Button 
                variant="outline" 
                className="border-neutral-700"
                onClick={() => setShowDeleteConfirm(false)}
                disabled={deleting}
              >
                Cancel
              </Button>
              <Button 
                className="bg-red-500 hover:bg-red-600 text-white"
                onClick={handleDelete}
                disabled={deleting}
              >
                {deleting ? (
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                ) : (
                  <Trash2 className="w-4 h-4 mr-2" />
                )}
                Yes, Delete Permanently
              </Button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

function formatDuration(start: Date, end: Date): string {
  const totalSec = Math.max(0, Math.floor((end.getTime() - start.getTime()) / 1000));
  const h = Math.floor(totalSec / 3600);
  const m = Math.floor((totalSec % 3600) / 60);
  const s = totalSec % 60;
  if (h > 0) return `${h}h ${m}m ${s}s`;
  if (m > 0) return `${m}m ${s}s`;
  return `${s}s`;
}

function ScanEstimateDetail({ createdAt, maxMin = 20 }: { createdAt: string; maxMin?: number }) {
  const elapsed = Math.floor((Date.now() - new Date(createdAt).getTime()) / 60000);
  if (elapsed > maxMin) return <p className="text-xs text-neutral-500 mt-1">⏱️ Taking longer than expected...</p>;
  return <p className="text-xs text-neutral-500 mt-1">⏱️ ~{elapsed}/{maxMin} min</p>;
}

function generateMarkdownReport(
  test: TestData['test'],
  results: TestResult[],
  summary: TestData['summary'],
  benchmark: { available: boolean; percentile?: number; totalScans?: number; avgScore?: number; medianScore?: number } | null,
): string {
  const grade = test.score !== null 
    ? (test.score >= 90 ? "A" : test.score >= 80 ? "B" : test.score >= 70 ? "C" : test.score >= 60 ? "D" : "F")
    : "?";
  
  const failed = results.filter(r => !r.passed);
  
  let md = `# 🛡️ PwnClaw Security Report\n\n`;
  md += `**Agent:** ${test.agentName}\n`;
  md += `**Date:** ${new Date(test.createdAt).toLocaleString()}\n`;
  md += `**Score:** ${test.score}/100 (Grade ${grade})\n\n`;
  
  md += `## Summary\n\n`;
  md += `| Metric | Value |\n|--------|-------|\n`;
  md += `| Total Attacks | ${summary.total} |\n`;
  md += `| Passed | ${summary.passed} |\n`;
  md += `| Failed | ${summary.failed} |\n`;
  md += `| Critical | ${summary.bySeverity.critical} |\n`;
  md += `| High | ${summary.bySeverity.high} |\n`;
  md += `| Medium/Low | ${summary.bySeverity.medium + summary.bySeverity.low} |\n\n`;
  
  if (benchmark?.available) {
    md += `## Benchmark\n\n`;
    md += `Better than **${benchmark.percentile}%** of all tested agents (${benchmark.totalScans} scans, avg ${benchmark.avgScore}/100).\n\n`;
  }
  
  if (failed.length > 0) {
    md += `## Vulnerabilities Found\n\n`;
    for (const r of failed) {
      md += `### ❌ ${r.attackName} [${(r.severity || 'medium').toUpperCase()}]\n\n`;
      md += `**Category:** ${r.category}\n\n`;
      md += `**Attack Prompt:**\n\`\`\`\n${r.promptPreview || r.prompt}\n\`\`\`\n\n`;
      md += `**Agent Response:**\n\`\`\`\n${r.response}\n\`\`\`\n\n`;
      md += `**Analysis:** ${r.analysis?.split('\n\n📋 Fix Instruction')[0] || ''}\n\n`;
      if (r.analysis?.includes('📋 Fix Instruction')) {
        const fix = r.analysis.split('📋 Fix Instruction (copy-paste to your agent\'s system prompt):\n')[1]?.trim();
        if (fix) md += `**Fix Instruction:**\n\`\`\`\n${fix}\n\`\`\`\n\n`;
      }
      md += `---\n\n`;
    }
  }
  
  const passed = results.filter(r => r.passed);
  if (passed.length > 0) {
    md += `## Passed Attacks (${passed.length})\n\n`;
    for (const r of passed) {
      md += `- ✅ ${r.attackName} (${r.category})\n`;
    }
    md += `\n`;
  }
  
  md += `---\n*Generated by [PwnClaw](https://www.pwnclaw.com) — AI Agent Security Testing*\n`;
  return md;
}
