ALTER TABLE tests ADD COLUMN IF NOT EXISTS model_name TEXT;
ALTER TABLE tests ADD COLUMN IF NOT EXISTS framework TEXT;
ALTER TABLE benchmarks ADD COLUMN IF NOT EXISTS model_name TEXT;
ALTER TABLE benchmarks ADD COLUMN IF NOT EXISTS framework TEXT;
